services:
  - type: web
    name: eltopup-be
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: SUPABASE_PROJECT_REF
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: ROBUXSHIP_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
